### ISSUE TITLE
No codes for error messages.

### ISSUE THREAD

**Issue by KunalGhosh02** [technojam/technojam-backend#12]
An error code should be sent along with error message to handle exceptions better. 
Is:
>return res.status(400).json({ msg: 'Email doesnt exist' });

Should be:

>return res.status(400).json({ code: 'EMAIL_NOT_FOUND ', msg: 'Email doesnt exist' });

Relevant section: /routes

**Comment by lazycipher** [comment]
@KunalGhosh02 Go ahead if you wish to work on this issue!
But before that, Can you share the list of codes that you'll be using?

Use the `development` branch to work on the issue.

**Comment by KunalGhosh02** [comment]
**List of error codes:**
---
`const serverError = "SERVER_ERROR";`

**Route: contact**

POST: 

path / (submit new)

if 200 `QUERY_SUBMIT_DONE` 
if 400 `QUERY_SUBMIT_FAILED`
if 500 `serverError`

DELETE:

path / (detele queries)

if 401 `QUERY_DELETE_UNAUTHORISED`
    onSuccess `QUERY_DELETE_DONE` 
    onFailure `QUERY_DELETE_FAILED`
if 500 `serverError`

GET:

path / (fetch queries)

if 401 `QUERY_FETCH_UNAUTHORISED`
    onFailure `QUERY_FETCH_ERROR`
if 500 `serverError`

**Route: events**

GET:

path / (events)

if 500 `serverError`

path /:eventID (get event details using event ID)

if 404 `EVENTS_EVENTID_NOT_FOUND`
if 500 `serverError`

path /participants/:eventID (participants of event ID)

if 500 `serverError`

POST:

path /add (add events)

if 401 `EVENTS_ADD_UNAUTHORISED`
    onSuccess `EVENTS_ADD_DONE`
    onFailure `EVENTS_ADD_FAILED`
if 500 `serverError`

PUT:

path /register/:eventID (register user to event ID)

if 400 `EVENTS_REGISTER_REDUNDANT`
    onSuccess
        if 201 `EVENTS_REGISTER_DONE`
        if 400 `EVENTS_REGISTER_FAILED`
    onFailure `serverError`

DELETE:

path /detele/:eventID (detele an event with event ID)

https://github.com/technojam/technojam-backend/blob/9589c5669e424b813fb19c68a09c03b13590bf96/src/routes/events.js#L115

*Should be 401*

if 401 `EVENTS_DELETE_UNAUTHORISED`
    onSuccess `EVENTS_DELETE_DONE`
    onFailure `EVENTS_DELETE_FAILED`
if 500 `serverError`

**Route: groups**

GET:

path / (List groups)

if 500 `serverError`

POST:

path / (Add group)

if 401 `GROUPS_ADD_UNAUTHORISED`
    onSuccess `GROUPS_ADD_DONE`
    onFailure `GROUPS_ADD_FAILED`
if 500 `serverError`

DELETE:

path /detele/:groupID

https://github.com/technojam/technojam-backend/blob/9589c5669e424b813fb19c68a09c03b13590bf96/src/routes/groups.js#L49

*Should be 401*

if 401 `GROUPS_DELETE_UNAUTHORISED`
    onSuccess `GROUPS_DELETE_DONE`
    onFailure `GROUPS_DELETE_FAILED`
if 500 `serverError`

**Route: login**

GET:

path / (Get user)

if 500 `serverError`

PUT:

path / (Update user info)

onSuccess `LOGIN_USER_UPDATE_DONE`
if 500 `serverError`

POST:

path / (User Authentication)

if 400 `LOGIN_USER_BAD_REQUEST`
if 401 `LOGIN_USER_UNAUTHORISED`
if 500 `serverError`

**Route: projects**

GET:

path / (Get projects list)

if 500 `serverError`

POST:

if 401 `PROJECTS_ADD_UNAUTHORISED`
    onSuccess 201 `PROJECTS_ADD_DONE`
    onFailure 400 `PROJECTS_ADD_FAILED`
if 500 `serverError`

DELETE:

/:projectID/detele

https://github.com/technojam/technojam-backend/blob/9589c5669e424b813fb19c68a09c03b13590bf96/src/routes/projects.js#L49

*Should be 401*

if 401 `PROJECTS_DELETE_UNAUTHORISED`
    onSuccess `PROJECTS_DELETE_DONE`
    onFailure `PROJECTS_DELETE_FAILED`
if 500 `serverError`

**Route: register**

POST:

path / (Register user)

if 400 `REGISTER_CREATE_REDUNDANT`
    onSuccess 201 `REGISTER_CREATE_DONE`
if 500 `serverError`

**Route: verification**

*PLAESE UPDATE VERIFICATION ROUTE TO SEND VALID JSON RESPONSE*

GET:

path / (Check token state)

if !token `VERIFICATION_TOKEN_GONE`
if !user `VERIFICATION_USER_NOT_FOUND`
if user.isVerified `VERIFICATION_USER_REDUNDANT`
if 401 `VERIFICATION_TOKEN_UNAUTHORISED`
    onSuccess `VERIFICATION_USER_VERIFY`
    onFailure `VERIFICATION_TOKEN_NOT_FOUND`

PATCH:

path / (Verify with token)

if !token `VERIFICATION_VERIFY_TOKEN_GONE`
if !user `VERIFICATION_VERIFY_USER_NOT_FOUND`
if user.isVerified `VERIFICATION_VERIFY_USER_REDUNDANT`
       onSuccess => 
                      onSuccess `VERIFICATION_VERIFY_USER_DONE`
                      onFailure `serverError`

https://github.com/technojam/technojam-backend/blob/9589c5669e424b813fb19c68a09c03b13590bf96/src/routes/verification.js#L84

*Should be 412*

POST:

path /resend (Re send verification mail)

if !user `VERIFICATION_RESEND_USER_NOT_FOUND`
if user.isVerified `VERIFICATION_RESEND_VERIFY_USER_REDUNDANT`
    onSuccess `VERIFICATION_RESEND_DONE`

if 500 `serverError`

---


@lazycipher **Please review and add modifications if any.**

**Comment by lazycipher** [comment]
@KunalGhosh02 Create a PR

**Comment by KunalGhosh02** [comment]
Fixed and merged to development.
#16
