### ISSUE TITLE
Create GET and POST endpoints for events

### ISSUE THREAD

**Issue by 20manas** [technojam/technojam-backend#2]
## Here are a few important questions:

1. Which attributes should each event contain (name, description, date, venue, etc)?
2. Which database should be used for storing events? Ideally it should be either PostgreSQL or MongoDB.
@dwivediabhimanyu @aanurraj @Prakhar-Srivastava , etc...

**Comment by lazycipher** [comment]
Hii @20manas,
1. Collaborate with @dwivediabhimanyu, @ravisaxena23, @AmanRawat882, and @Shivamdot for the attributed thing on slack.
2. We'll be using a No-SQL database for sure. I'm thinking of MongoDB. What do you say?

**Comment by rakaar** [comment]
Would like to work on it. Can you provide more details?

**Comment by ravisaxena23** [comment]
We are making the basic infrastructure right now umm it is not open right now for issue..yes you can work on it it would be our pleasure but not right now in upcoming 4 5 days..we will pass on the details thank you sir

**Comment by ravisaxena23** [comment]
if you really love backend you can work here and ask for issues https://github.com/honeycoder96/TempBackEnd

**Comment by rakaar** [comment]
Sure @ravisaxena23 , would be interested  to contribute. I have marked the repos under watch. Will start working once more issues that are open are created . 
Thank you
