### ISSUE TITLE
Once user forgets his/her password he cant re-authenticate with new pwd.

### ISSUE THREAD

**Issue by danishjamal104** [technojam/technojam-backend#21]
## Steps for reseting password.
1. A route for the forgot password.
2. Configure nodemailer to send email templates
3. Create email template
4. Method to send password confirmation
5. A route to confirm password reset.
6. Method to generate and token send to the user’s email.

**Comment by danishjamal104** [comment]
I am working on this issue..

**Comment by lakshya-20** [comment]
Hey! @danishjamal104 the issue is resolved now, Thank you :)
