### ISSUE TITLE
Modify userSchema

### ISSUE THREAD

**Issue by lakshya-20** [technojam/technojam-backend#26]
Add the below-mentioned fields in UserSchema.
- Github Profile Url (type:String, required:false)
- Linked Profile Url (type:String, required:false)

**Comment by arpancodes** [comment]
Hello @lakshya-20 this is my first hacktoberfest and I think I can do this one... Please assign it to me 😄

**Comment by mghizzo** [comment]
Can you assign this to me?

**Comment by arpancodes** [comment]
Hey @AtzManuel, even though it's not assigned to me yet, I have already cloned and started working on it... and almost finished 😄 do you mind me completing this?

**Comment by mghizzo** [comment]
@arpancodes I've already made this, but If you want I'll just leave this to you.

**Comment by arpancodes** [comment]
Thankyou 😄

**Comment by lakshya-20** [comment]
@arpancodes I have got your pr.
It's working fine!
